Xiangfei modify table
TheRARELab/fetch_gazebo pull request #1
Opened 2024-07-15 01:07 UTC by xiangfeikong777

2024-07-15 01:08 UTC, xiangfeikong777 commented
[Screencast from 07-13-2024 10:00:28 PM.webm](https://github.com/user-attachments/assets/5b9bf76a-eae5-4783-88df-fd608156a070)
@umhan35 Please review the PR and video!

2024-07-15 01:37 UTC, umhan35 requested changes
Very good initial attempt!

2024-07-15 01:37 UTC, umhan35 commented on fetchit_challenge/models/caddy_green/model.sdf
All other models should not be changed. Please revert all of them.

2024-07-15 01:37 UTC, umhan35 commented on fetchit_challenge/models/caddy_green/model.sdf
Why changing 0 to 1?

2024-07-15 01:37 UTC, umhan35 commented on fetchit_challenge/launch/nec0115a_arena_rarelab2024_highlights.launch
Include the Fetch robot here. Take a look at the original launch file.

2024-07-15 01:37 UTC, umhan35 commented on fetchit_challenge/models/rarelab_long_table/meshes/EM.png
EM here is a logo that we don't have in front of our tables. We need to use [fetchit_table](https://github.com/TheRARELab/fetch_gazebo/tree/gazebo9/fetchit_challenge/models/fetchit_table) instead of 
[fetchit_table_em](https://github.com/TheRARELab/fetch_gazebo/tree/gazebo9/fetchit_challenge/models/fetchit_table_em).

2024-07-15 01:37 UTC, umhan35 commented on fetchit_challenge/models/rarelab_long_table/meshes/table_EM.dae
> +    <image id="EM_png" name="EM_png">
Do a diff with [simple.dae](https://github.com/TheRARELab/fetch_gazebo/blob/gazebo9/fetchit_challenge/models/fetchit_table/meshes/simple.dae) to remove the use of EM logo

2024-07-15 01:37 UTC, umhan35 commented on fetchit_challenge/models/rarelab_long_table/model.config
> +</model>
👍

2024-07-15 01:37 UTC, umhan35 commented on fetchit_challenge/models/rarelab_long_table/meshes/table_EM.dae
Where is this file used?

2024-07-15 01:37 UTC, umhan35 commented on fetchit_challenge/nodes/shunk_machine_controlers.pyc
pyc files are not related to this change, so they should not be here.

2024-07-15 01:37 UTC, umhan35 commented on fetchit_challenge/nodes/shunk_machine_controlers.pyc
In general, we only want to include the files that are related to this change you make. That means you need to go through each file name to stage them (See https://www.vishalon.net/blog/git-gui-stage-individual-unstaged-file).

2024-07-15 01:37 UTC, umhan35 commented on fetchit_challenge/models/rarelab_long_table/model.sdf
> +              <size>1.524 0.61 0.75</size>
What are those values? Should this be used: https://github.com/TheRARELab/fetch_gazebo/blob/gazebo9/fetchit_challenge/models/fetchit_table/model.sdf#L17-L32?

2024-07-15 01:39 UTC, umhan35 commented
Why is it closed...? Restore the branch and reopen it? 

<img width="861" alt="image" src="https://github.com/user-attachments/assets/f6a033ab-e1bb-4095-abbe-9de9852fe3aa">

2024-07-15 06:02 UTC, xiangfeikong777 commented
@umhan35 
[Screencast from 07-15-2024 01:59:37 AM.webm](https://github.com/user-attachments/assets/56c7bc47-e282-4171-9b89-196dc19336e6)
Please review my all push and video.

2024-07-15 15:29 UTC, umhan35 commented on fetchit_challenge/models/rarelab_long_table/meshes/simple.dae
Remove this file because it is not used anywhere?

2024-07-15 15:39 UTC, umhan35 commented
I just made a few changes. Can you test it by pulling the changes and opening the launch file?

2024-07-15 15:50 UTC, xiangfeikong777 commented
> I just made a few changes. Can you test it by pulling the changes and opening the launch file?
Yes, I did git pull and tested it, everything looks good.
[Screencast from 07-15-2024 11:49:21 AM.webm](https://github.com/user-attachments/assets/2e149eed-78b9-4ca2-a2da-2135f6da5abf)

2024-07-15 15:53 UTC, umhan35 commented
I changed some stuff to make things simpler. Can you test it again?

2024-07-15 15:54 UTC, umhan35 commented
1s making another change

2024-07-15 15:59 UTC, umhan35 commented
Ok. I created a non-highlights version (a lunch file and a world file) because the environment in the highlights version is too bright. Can you test it as well as the highlights version?

2024-07-15 16:34 UTC, xiangfeikong777 commented
> Ok. I created a non-highlights version (a lunch file and a world file) because the environment in the highlights version is too bright. Can you test it as well as the highlights version?

Test for nec0115a_arena.launch: 
[Screencast from 07-15-2024 12:25:15 PM.webm](https://github.com/user-attachments/assets/f99bc3ae-ecd8-4d2c-94a9-22a96a01d939)


Test for nec0115a_arena_highlights.launch:
[Screencast from 07-15-2024 12:31:23 PM.webm](https://github.com/user-attachments/assets/4b8296c7-2521-42aa-85b5-94e8e8c43207)

2024-07-15 16:46 UTC, umhan35 commented
Great! The non-highlights version is better: Now we can see them in their original gray.

But the tables are too white to see. Can you change it to light gray? And then we can close this issue.

2024-07-15 20:40 UTC, xiangfeikong777 commented
> issu
screenshot for nec0115a_arena.launch:
![nec0115a_arena](https://github.com/user-attachments/assets/f8a875b4-4aff-41dd-b4d2-c8483a088741)

screenshot for nec0115a_arena._highlights.launch:
![nec0115a_arena_highlights](https://github.com/user-attachments/assets/7f216a23-73f5-4f5c-8f7e-72f51393a2f7)


@umhan35

2024-07-15 21:16 UTC, xiangfeikong777 commented
> Great! The non-highlights version is better: Now we can see them in their original gray.
> 
> But the tables are too white to see. Can you change it to light gray? And then we can close this issue.

Below is the screenshot for the highlights arenas for modify the table color to light grey:
![highlights](https://github.com/user-attachments/assets/70e01859-0afc-4926-9cda-eb41cde1d90b)

Without highlight:
![no_highlights](https://github.com/user-attachments/assets/77b579e4-5d76-4dbb-b5c4-81778531befd)
@umhan35

2024-07-15 21:46 UTC, umhan35 commented
Really weird that the tables do not have any shadows in both worlds. Is the white table better or the light gray one?

2024-07-15 22:39 UTC, xiangfeikong777 commented
> Really weird that the tables do not have any shadows in both worlds. Is the white table better or the light gray one?

For the non highlight version, I think the gray table is better, but for the highlights version, the white table looks more better but have the issue for too light as you said before.

2024-07-15 23:16 UTC, umhan35 commented
Cool. Push the light gray changes and let's merge this.

2024-07-16 03:36 UTC, umhan35 approved these changes

2024-07-16 03:36 UTC, merged